version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    # Only create pull requests to update lockfiles. Ignore any new versions that would require package manifest changes.
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "Maintenance:"
    assignees:
      - mg
  - package-ecosystem: "npm"
    directory: "/"
    # Always increase the version requirement to match the new version.
    versioning-strategy: increase
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "Maintenance:"
    assignees:
      - dk
